---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role themes
#
themes_service_name: "edx-themes"
themes_user: "{{ themes_service_name }}"
themes_home: "{{ COMMON_CFG_DIR }}/{{ themes_service_name }}"
themes_code_dir: "{{ themes_home }}/{{ themes_service_name }}"

THEMES_GIT_IDENTITY: !!null
THEMES_GIT_PROTOCOL: 'ssh'
THEMES_GIT_MIRROR: "{{ COMMON_GIT_MIRROR }}"
THEMES_GIT_PATH: "{{ COMMON_GIT_PATH }}"
THEMES_REPO: "edx-themes.git"
THEMES_VERSION: "master"


THEMES_REPOS:
  - PROTOCOL: "{{ THEMES_GIT_PROTOCOL }}"
    DOMAIN: "{{ THEMES_GIT_MIRROR }}"
    PATH: "{{ THEMES_GIT_PATH }}"
    REPO: "{{ THEMES_REPO }}"
    VERSION: "{{ THEMES_VERSION }}"
    DESTINATION: "{{ themes_code_dir }}"
    SSH_KEY: "{{ THEMES_GIT_IDENTITY }}"
